hash-format = "sha256"

[[files]]
file = "mods/advancedperipherals.pw.toml"
hash = "dcd8ef0c893409cc74a0a401854d71d40b319ebfe4f7d64be691f832efe4e7d5"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "ed45c352a49b65c7221e57d979d0c6935522dfef4968aa5b7421f4d3e670ce40"
metafile = true

[[files]]
file = "mods/ars-energistique.pw.toml"
hash = "8ad679c28c8d8ebf85609b571b4556bfd9f605506efbaa6907a3045c965ce8b8"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "e3ff7d98944e1114a528fbd667ae5a552420084c3346ace13bbf4be8d5f8618e"
metafile = true

[[files]]
file = "mods/astral-dragon.pw.toml"
hash = "86f6de9cfdedd5525dfcfce4ab19b4d5839a1ff51aa0b56535bd570f4a3b4b35"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "547660bb17452fae6e46504c87eea9e75eeb50de440495cadcee9ad49c6d131d"
metafile = true

[[files]]
file = "mods/better-library.pw.toml"
hash = "067421670e4da3f6acab7f147baf462482faf526c414828a87088640bac34052"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "925953631ee34a79f4dc5cf9ff9b9cb642435be0eccbf3184510659002bbda4d"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "47e9b46467cef24a838b55407bb7e7679d7c70574a0ac992bc9d31609e833458"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "af5be21b70b778bd919a8d10807895fad40671c9701519dbf95bc74f139fec3f"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/coastal-waves.pw.toml"
hash = "7543f3dbc193d98b67b760b4e7a7a5f5a8bbd58c66d4ebcb13d6729eb6017cff"
metafile = true

[[files]]
file = "mods/create-applied-kinetics.pw.toml"
hash = "4520f1b7da2cad5e8c8cf0babfd524b322dc2e8fe1b2d7e7b93c365d1779ea14"
metafile = true

[[files]]
file = "mods/create-mechanical-spawner.pw.toml"
hash = "e9dce7730d04e7d7f44c6216fefa0897b361ece8a74ea4c474f9d986e2c0dcc5"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9da22561c3a5e45beb91121518a49f2e8a62bedb332574ce43a9d9b287ebc705"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "61e80b0de7d4991cb6ebae3c826d4b51a3e78e18c35f4730e9741603ab7cb18a"
metafile = true

[[files]]
file = "mods/createnuclear.pw.toml"
hash = "e7a6cda82ddd91e08e2fbadff97d4590861f0ca78d9fa12a8693de25f48a58ac"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "61ce79aeecd3101399a33bbea16444736f2988b363a63c9f3b6a2c4fb0b3828a"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "be9e923b0d2523ecae452b00c8bb65c6f7e03e6b89f5567be566ca7a0e467c7f"
metafile = true

[[files]]
file = "mods/dragons-survival.pw.toml"
hash = "1730a58d5b959d0aca177ec225e428898c406c844795e97f8e80b312ddbad052"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "d93c3c494955dfc44e2590ded2ee8414d582e87f2fca00575f08576ae2197d57"
metafile = true

[[files]]
file = "mods/formations-nether.pw.toml"
hash = "cfdef44464ccf6c3a9b0fa7a48bbbfa40049765c01c3aaf225fddd167cd5eeec"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
hash = "c52b32923563ae28647a9429c5acb66c74d76c6f6ae4ffa8d08fc75626cc0115"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
hash = "41ea41c71242b710df4768bdd0f3f2433c64600d2d1405472c01993bd7f5da25"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e448ed8448354d972dcd3ef7c46833e58de16147fe947a969538bf80efad6de9"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "b8aee2057378b6f054f94550684d9a3f41ded7cc47794c8b01c107c8c2115ceb"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "b07188b12d6d568dc825d4d50cf01dae40795a933647c887c1d7f49ee783f2f4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "62cd07874e73d82b29ff6fecd5345ce4b1135ce7ff29f3ef695139be33157483"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5367193d3f87b7bc5a81bcd64a5b96a843e76d4df7a83c8bb7e1911aa82dd52e"
metafile = true

[[files]]
file = "mods/mechanicals-lib.pw.toml"
hash = "4e3aaef188d1f975c6ebd539f50021768851f7fc4638079ee72179ec33bf487f"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "d3e8ccad3df70178a9e420827a4e85932b8a07c76b24d3fcf42fd4949a304b88"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "bc9449306cb2c32f16347779291d68e5fba67f85d7aca04b4b9cc1c033ec4083"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
hash = "2488bf19149e671ab9fc63823029b19ebae6c4eeabb7ff748c0be341758a246b"
metafile = true

[[files]]
file = "mods/sgjourney.pw.toml"
hash = "d7a1b92ee60f56522dd394d61122ffd7c196fb131f64dda1720f873d7efa7c16"
metafile = true

[[files]]
file = "mods/smallcolonies.pw.toml"
hash = "c46fa61a71eb6a9010dd8c275be955c4d58ad85184ef56d9c3a5ef7358706564"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "98894c50922dfad36e4313d798d4497a61c42ce855b44fd63aea79b4990cac5d"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "adc69a30b7ddf030a78f5b7994b6ded381626bc03de5a74566a7e24c98ebf139"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "63f25e4206eb8b5b77ca79a443941b31ef5085783fdf1af8255e8406bb7bba38"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "e6bb3eeda43411c95fa84549ba3281df62654e36140ec322190206fc8df512a4"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "579f3e14189fccf73e931abe4a00344b9aa1b130a069542c6b90e4906b4d91ae"
metafile = true

[[files]]
file = "mods/spring-to-life-backport.pw.toml"
hash = "e89cc68722b5e8a52baa44e9cb31c61b4ccd7fc0de8a61a0bb9a9c8ffccfc709"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "a4e86a4148175abab9c98b466d2148d860f957ed106c0ec3da7cb361fbecce16"
metafile = true

[[files]]
file = "mods/subsurface.pw.toml"
hash = "a9ce0518bc6aaa80a3e2ca78e3182aac465c4ca0583ed2efe41cc7a52b2f5c1f"
metafile = true

[[files]]
file = "mods/telluriumforge.pw.toml"
hash = "7c354e50bf51143f3555cc8e5b296cecd5147b1f8f4f94e078445ec57839ee4d"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "a7074e8e499d34f5ce633dbd33f818e376dd1941ec5b1d97a33acd019df69b5a"
metafile = true

[[files]]
file = "mods/turtle-charging-station.pw.toml"
hash = "cc4f4a7698d1f40e2c6278436402dcb553ada9a568f8d7faa5de7be8c698b92a"
metafile = true

[[files]]
file = "mods/underground-village,-stoneholm.pw.toml"
hash = "9e5eedc2329699c885d2630198e7f2f00979f5eb74aed7acf362957df78454bf"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "634130ab233121c290fdb2567afd3939af6d98760c11f14db0426b64b8955894"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "4c2830674a08ec9f10af13e4d259aa60158bd306a3996d935e678281ec0cb5fd"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "ee63a5958eb1e0238257e2064d917bdaf8e528a47904bdfbe04a5758a1537e9f"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "0cc13a86488cf89d2989edc1636fa63c7efa2fe819246d42af35113458d5ba5b"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "c0e40691651465b4eb1037749148c2078123604195e19b582dbef3cd5914e3b1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9492d0854c51570bf2a6bace6267262e7573b94c40d721348996617e5d99480a"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "1a33e6d64e88ad59b65d126c6457d582e62724167349ea184eb237435298985e"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e2b23d0a1bf228d37ff8c3330150c24eb19cb875e113fae543191f34ded92ff8"
metafile = true
