name = "Magic Skies"
author = "Adam"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "798ab1e2ccd934b1986924c8ef79549e5eb4075b45416d0e21b60ea3b94b6635"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
